[package]
name = "quantris"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = "0.12"
rand = "0.8.5"
nalgebra = "0.32.3"

[profile.release]
opt-level = 'z'
lto = true
strip = true
codegen-units = 1

